<a href="https://colab.research.google.com/github/Alagucodein/Pythonlearning/blob/main/DataCleaning_LoanData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
from google.colab import files
file = files.upload()

Saving Loan-Approval-Prediction.csv to Loan-Approval-Prediction.csv

In [4]:
df = pd.read_csv('Loan-Approval-Prediction.csv')

In [5]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [8]:
df.shape

(614, 13)

In [9]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [10]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [12]:
df.iloc[420:456]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
420,LP002348,Male,Yes,0,Graduate,No,5829,0.000000,138.0,360.0,1.0,Rural,Y
421,LP002357,Female,No,0,Not Graduate,No,2720,0.000000,80.0,NaN,0.0,Urban,N
422,LP002361,Male,Yes,0,Graduate,No,1820,1719.000000,100.0,360.0,1.0,Urban,Y
423,LP002362,Male,Yes,1,Graduate,No,7250,1667.000000,110.0,NaN,0.0,Urban,N
424,LP002364,Male,Yes,0,Graduate,No,14880,0.000000,96.0,360.0,1.0,Semiurban,Y
425,LP002366,Male,Yes,0,Graduate,No,2666,4300.000000,121.0,360.0,1.0,Rural,Y
426,LP002367,Female,No,1,Not Graduate,No,4606,0.000000,81.0,360.0,1.0,Rural,N
427,LP002368,Male,Yes,2,Graduate,No,5935,0.000000,133.0,360.0,1.0,Semiurban,Y
428,LP002369,Male,Yes,0,Graduate,No,2920,16.120001,87.0,360.0,1.0,Rural,Y
429,LP002370,Male,No,0,Not Graduate,No,2717,0.000000,60.0,180.0,1.0,Urban,Y
430,LP002377,Female,No,1,Graduate,Yes,8624,0.000000,150.0,360.0,1.0,Semiurban,Y
431,LP002379,Male,No,0,Graduate,No,6500,0.000000,105.0,360.0,0.0,Rural,N
432,LP002386,Male,No,0,Graduate,NaN,12876,0.000000,405.0,360.0,1.0,Semiurban,Y
433,LP002387,Male,Yes,0,Graduate,No,2425,2340.000000,143.0,360.0,1.0,Semiurban,Y
434,LP002390,Male,No,0,Graduate,No,3750,0.000000,100.0,360.0,1.0,Urban,Y
435,LP002393,Female,NaN,NaN,Graduate,No,10047,0.000000,NaN,240.0,1.0,Semiurban,Y
436,LP002398,Male,No,0,Graduate,No,1926,1851.000000,50.0,360.0,1.0,Semiurban,Y
437,LP002401,Male,Yes,0,Graduate,No,2213,1125.000000,NaN,360.0,1.0,Urban,Y
438,LP002403,Male,No,0,Graduate,Yes,10416,0.000000,187.0,360.0,0.0,Urban,N
439,LP002407,Female,Yes,0,Not Graduate,Yes,7142,0.000000,138.0,360.0,1.0,Rural,Y
440,LP002408,Male,No,0,Graduate,No,3660,5064.000000,187.0,360.0,1.0,Semiurban,Y
441,LP002409,Male,Yes,0,Graduate,No,7901,1833.000000,180.0,360.0,1.0,Rural,Y
442,LP002418,Male,No,3+,Not Graduate,No,4707,1993.000000,148.0,360.0,1.0,Semiurban,Y
443,LP002422,Male,No,1,Graduate,No,37719,0.000000,152.0,360.0,1.0,Semiurban,Y
444,LP002424,Male,Yes,0,Graduate,No,7333,8333.000000,175.0,300.0,NaN,Rural,Y
445,LP002429,Male,Yes,1,Graduate,Yes,3466,1210.000000,130.0,360.0,1.0,Rural,Y
446,LP002434,Male,Yes,2,Not Graduate,No,4652,0.000000,110.0,360.0,1.0,Rural,Y
447,LP002435,Male,Yes,0,Graduate,NaN,3539,1376.000000,55.0,360.0,1.0,Rural,N
448,LP002443,Male,Yes,2,Graduate,No,3340,1710.000000,150.0,360.0,0.0,Rural,N
449,LP002444,Male,No,1,Not Graduate,Yes,2769,1542.000000,190.0,360.0,NaN,Semiurban,N
450,LP002446,Male,Yes,2,Not Graduate,No,2309,1255.000000,125.0,360.0,0.0,Rural,N
451,LP002447,Male,Yes,2,Not Graduate,No,1958,1456.000000,60.0,300.0,NaN,Urban,Y
452,LP002448,Male,Yes,0,Graduate,No,3948,1733.000000,149.0,360.0,0.0,Rural,N
453,LP002449,Male,Yes,0,Graduate,No,2483,2466.000000,90.0,180.0,0.0,Rural,Y
454,LP002453,Male,No,0,Graduate,Yes,7085,0.000000,84.0,360.0,1.0,Semiurban,Y
455,LP002455,Male,Yes,2,Graduate,No,3859,0.000000,96.0,360.0,1.0,Semiurban,Y

In [13]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

Columns un wanted
LoanId, Married, CoapplicantIncome, property_area

In [14]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [15]:
#data cleaning
df.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
df1 = df.dropna()

In [17]:
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [18]:
df1.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [22]:
df1.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64